# Using Node.js as a base image
FROM node:22-slim

# Set the working directory inside the container to /app
WORKDIR /app

# Install Yarn
RUN npm install yarn

# Copy package.json and yarn.lock into the container
COPY package.json yarn.lock ./

# Installing dependencies
RUN npm i --legacy-peer-deps
RUN yarn install

# Copying the env file
COPY .env .env

# Copy the rest of the application code into the container
COPY . .

# Build the application
RUN yarn build

# Expose the port that frontend will run on
EXPOSE 3000

# Command to start the application
CMD ["yarn", "start"]