services:
  backend:
    build:
      context: ./backend
      dockerfile: DockerFile
    ports:
      - "8000:8000" 
    depends_on:
      - sockets 

  sockets:
    build:
      context: ./socket
      dockerfile: DockerFile
    ports:
      - "4000:4000"