# Using Node.js as a base image
FROM node:22-slim

# Set the working directory inside the container to /app
WORKDIR /app

# Copying package.json and package-lock.json into the container
COPY package.json package-lock.json ./

# Installing dependencies using npm
RUN npm install

# Copying the env file
COPY config/.env .env

# Copy the rest of the application code into the container
COPY . .

# Exposing the port that backend will run on
EXPOSE 8000

# Command to start the application
CMD ["node", "server.js"]