# Use Node.js as a base image
FROM node:22-slim

# Set the working directory inside the container to /app
WORKDIR /app

# Copy package.json and package-lock.json into the container
COPY package.json package-lock.json ./

# Install dependencies using npm
RUN npm install

# Copy the .env file
COPY .env .env

# Copy the rest of the application code into the container
COPY . ./

# Expose the port dynamically or set a default for the sockets service
EXPOSE 4000

# Command to start the sockets service
CMD ["node", "index.js"]
